sudo: required
language: generic 
services:
    - docker

before_install:
    - docker build -t r/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true r/docker-react npm run test -- --coverage